### ISSUE TITLE
Part of the face changes？

### ISSUE THREAD

**Issue by SeanLiu081** [VinAIResearch/CPM#32]
Only half of the face changes skin color. How to make the whole face change skin color?
![image](https://github.com/VinAIResearch/CPM/assets/26735847/898df865-ea65-4fc2-8d7c-345b513b6405)
![企业微信截图_16944150875146](https://github.com/VinAIResearch/CPM/assets/26735847/5cea3ace-9bc0-407d-86b9-73e8f03ee5e6)

**Comment by thaoshibe** [comment]
Yes, it's a limitation of our approach. We can only perform makeup on [this facial area](https://github.com/VinAIResearch/CPM/blob/main/PRNet/uv-data/uv_face.png). This is because we used [PRNet](https://github.com/yfeng95/PRNet#joint-3d-face-reconstruction-and-dense-alignment-with-position-map-regression-network), which is not a full-face 3D model. You might want to replace PRNet with other full-face model for better results.
