### ISSUE TITLE
Color Training

### ISSUE THREAD

**Issue by pirate-zhang** [VinAIResearch/CPM#5]
When i try to train the Color Branch,there is a error occurred.Could you give me a suggestion when you have time.
The error message is as follows:
Traceback (most recent call last):
  File "create_beautygan_uv.py", line 51, in <module>
    uv_texture, uv_seg = generator.get_texture(image, seg)
  File "/data/run01/scv0004/CPM-main/Color/texture_generator.py", line 23, in get_texture
    pos[:, :, :2].astype(np.float32),
TypeError: 'NoneType' object is not subscriptable
![image](https://user-images.githubusercontent.com/58171157/118457538-70921d00-b72c-11eb-880c-41c9b5c3e5d4.png)

**Comment by thaoshibe** [comment]
Hello there, I guess there's something wrong with that image.
Could you change the line [here ](https://github.com/VinAIResearch/CPM/blob/e9bf65752f9230f9cf15dd93cb68ae15db4a5cdf/Color/create_beautygan_uv.py#L51) to this:

`try:
	uv_texture, uv_seg = generator.get_texture(image, seg)
except:
	print('Something wrong with: ', list_imgs[i])
`
And we'll look at that image later.
I've faced that issues before, it turned out that there's no faces in the images; Or dlib couldn't detect any faces.

**Comment by thaoshibe** [comment]
Hi again,
If there's something wrong with the images (no face, degraded, corrupted images, etc.), then I can't help.
Else, dlib couldn't detect any faces (very few cases)
Please handle these images by passing face's bounding boxes manually (Find more information [here](https://github.com/YadiraF/PRNet#prerequisite))

I'm closing this issue and hope you can run the code smoothly!
