### ISSUE TITLE
higher resolution

### ISSUE THREAD

**Issue by Yijunmaverick** [VinAIResearch/CPM#6]
Thanks for sharing.

Is it possible to run this method on higher-resolution input? or 256 only?

**Comment by thaoshibe** [comment]
Appreciate your question!
Resolution is not a fundamental constraint of CPM. We can use a higher resolution for sharper images.
For example, by using 512x512 UV maps, we can preserve the high-quality makeup patterns, as shown in the following figure.

![higher_resolution](https://user-images.githubusercontent.com/22058807/118930809-67918d80-b970-11eb-9c4e-163d33b9b1f5.png)
_(From left to right: 256x256 (as shown in the paper), 512x512 UV map, and reference image)_

**Comment by Yijunmaverick** [comment]
Thanks for the quick reply. Is 512 UV map obtained by another PRNet model or some upsampling technique? I may want to try ever larger size :)

**Comment by thaoshibe** [comment]
For the 512x512 UV map, I used _the same PRNet_ model (no need to retrain).
There's will be another `face_ind_512.txt`, `uv_kpt_ind_512.txt` files. (As your request, I'll upload it later).

---

But it worth noting about this method:

- **[01]** Basic (As shown in the paper):
Input -> UV (256) -> Color (256) | Pattern (256) -> Output Image (256)
- **[02]** Higher resolution UV (As shown in previous figure):
Input -> UV (**512**) -> Color (256) | Pattern (256)-> Output Image (**512**)
(Upsampling used in Pattern Mask & Color transferred TsmC)
- **[3]** "Wholesome" Solution:
Input -> UV (**512**) -> Color (**512**) | Pattern (**512**) -> Output Image (**512**)

I'm using **[2]** because that requires no re-train step (PRNet, Color, Pattern).
To be specific, **I do use upsampling for intermediate output** (Color Transferred (bicubic resize), Pattern Mask (nearest neighbor resize)). (See attached image)
![image](https://user-images.githubusercontent.com/22058807/118936450-c22de800-b976-11eb-8f2a-11f27bb564e2.png)
_(Getting higher resolution, based on [2])_

---

You might wonder why _didn't I use [3]_? Isn't it the best solution?
To do [3], we'll need to _re-train_ Color Branch & Pattern Branch.
It's feasible, but I haven't done the job due to: time-efficiency (it'll be super slow), dataset (most of the makeup datasets are 256x256 only), etc. ugh!

Hope this helps!

**Comment by Yijunmaverick** [comment]
Got it, thanks for explanation. The upsampling makes sense.
